// routes.gen.ts — auto-generated by vite-plugin-approuter. Do not edit.

import { createRootRoute, createRoute, createRouter } from '@tanstack/react-router'
import { lazy } from 'react'

const RootPage = lazy(() => import("./app/page"))
const AuthLoginPage = lazy(() => import("./app/(auth)/login/page"))
const AuthSignupPage = lazy(() => import("./app/(auth)/signup/page"))
const AboutPage = lazy(() => import("./app/about/page"))
const BlogPage = lazy(() => import("./app/blog/page"))
const BlogSlugPage = lazy(() => import("./app/blog/[slug]/page"))

// middleware.ts runs on the client. Do not use it as a security boundary.
const rootRoute = createRootRoute()
const route1 = createRoute({ getParentRoute: () => rootRoute, path: '/', component: RootPage })
const route2 = createRoute({ getParentRoute: () => rootRoute, path: "" })
const route3 = createRoute({ getParentRoute: () => route2, path: "login", component: AuthLoginPage })
const route3Tree = route3.addChildren([])
const route4 = createRoute({ getParentRoute: () => route2, path: "signup", component: AuthSignupPage })
const route4Tree = route4.addChildren([])
const route2Tree = route2.addChildren([route3Tree, route4Tree])
const route5 = createRoute({ getParentRoute: () => rootRoute, path: "about", component: AboutPage })
const route5Tree = route5.addChildren([])
const route6 = createRoute({ getParentRoute: () => rootRoute, path: "blog", component: BlogPage })
const route7 = createRoute({ getParentRoute: () => route6, path: "$slug", component: BlogSlugPage })
const route7Tree = route7.addChildren([])
const route6Tree = route6.addChildren([route7Tree])
const routeTree = rootRoute.addChildren([route1, route2Tree, route5Tree, route6Tree])

export const router = createRouter({ routeTree })
