import { promises as fs } from 'node:fs'
import path from 'node:path'

const HEADER = '// routes.gen.ts — auto-generated by vite-plugin-approuter. Do not edit.\n\n'

export async function writeRoutesFile(content: string, outFile: string): Promise<void> {
  const next = `${HEADER}${content}`
  await fs.mkdir(path.dirname(outFile), { recursive: true })

  let current: string | undefined
  try {
    current = await fs.readFile(outFile, 'utf8')
  } catch {
    current = undefined
  }

  if (current === next) return
  await fs.writeFile(outFile, next, 'utf8')
}
